version: "3.1"

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/perf-service
      - node_modules:/usr/src/perf-service/node_modules

volumes:
  node_modules: